<?php

namespace App\Services\AiAgentHub;

use App\Enums\Connection\Channel;
use Illuminate\Support\Str;

/**
 * Whether a turn is written, spoken, or both.
 *
 * The decision is made twice, because it has to be. Audio is generated by the
 * hub *during* the run, so asking for it is part of the request — before a
 * single word of the answer exists. Everything that depends on what the agent
 * actually said (a host and a port, a password, a numbered walkthrough, a wall
 * of text) can only be judged afterwards.
 *
 * So: decide() picks what to ask for, from the customer's side of the
 * conversation. reconsider() reads the finished answer and may add the written
 * version back — it never removes the voice, because by then it is paid for,
 * and a customer who asked to be spoken to should be spoken to.
 */
class AiDeliveryPolicy
{
    /** Modes an author can pick, in the order the form offers them. */
    public const MODE_DYNAMIC = 'dynamic';
    public const MODE_AUDIO_ONLY = 'audio_only';
    public const MODE_TEXT_AND_AUDIO = 'text_and_audio';
    public const MODE_TEXT_ONLY = 'text_only';

    public const MODES = [
        self::MODE_DYNAMIC,
        self::MODE_AUDIO_ONLY,
        self::MODE_TEXT_AND_AUDIO,
        self::MODE_TEXT_ONLY,
    ];

    /**
     * Past this, a voice note stops being a reply and becomes a lecture. The
     * written version goes along with it.
     */
    private const LONG_ANSWER_CHARS = 700;

    /**
     * Things nobody can act on by ear. Hearing "proxy.ipbr.pro porta oito zero
     * oito zero, usuário a-b-c" is not receiving that information — it is
     * being asked to write it down from dictation.
     */
    private const UNSPEAKABLE = [
        // Links, hosts, and anything with a port hanging off it.
        '~https?://~i',
        '~\bwww\.[a-z0-9-]+\.[a-z]{2,}~i',
        '~\b[a-z0-9][a-z0-9.-]*\.[a-z]{2,}:\d{2,5}\b~i',
        // Bare IPv4, with or without a port.
        '~\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b~',
        // Credentials, in the shapes support answers actually use.
        '~\b(usu[áa]rio|usuario|user(name)?|login|senha|password|passwd|token|chave|api[\s_-]?key)\b\s*[:=]~i',
        '~\b[\w.-]+:[^\s:@]{4,}@[\w.-]+~',
        // Fenced or inline code, and the long identifiers people copy.
        '~```~',
        '~\b[A-Za-z0-9_-]{24,}\b~',
    ];

    /**
     * What to ask the hub for, decided from the customer's side alone.
     *
     * @param  string  $mode  one of MODES
     * @param  bool  $customerSpoke        a voice note arrived in this turn
     * @param  bool  $voiceRequested       they asked to be answered out loud (sticky)
     * @param  bool  $lastReplyWasAudio    the agent's previous turn was spoken
     */
    public static function decide(
        string $mode,
        Channel $channel,
        bool $customerSpoke,
        bool $voiceRequested,
        bool $lastReplyWasAudio,
    ): string {
        // Nothing below matters where a voice note is not a message.
        if (! $channel->supportsVoiceReply() || $mode === self::MODE_TEXT_ONLY) {
            return self::MODE_TEXT_ONLY;
        }

        if ($mode !== self::MODE_DYNAMIC) {
            return $mode;
        }

        // An instruction outranks every heuristic below it: they said what
        // they want, and guessing over that is not being clever.
        if ($voiceRequested) {
            return self::MODE_AUDIO_ONLY;
        }

        // Answer in the medium they chose. Deliberately *not* alternated away
        // when they keep speaking: someone recording three voice notes in a row
        // is telling you how they prefer to talk.
        if ($customerSpoke) {
            return self::MODE_AUDIO_ONLY;
        }

        // They typed, and the agent's last turn was spoken. Two voice notes in
        // a row at somebody who is writing reads as not listening.
        if ($lastReplyWasAudio) {
            return self::MODE_TEXT_ONLY;
        }

        // A typed question gets a typed answer. Voice is what the customer
        // opens, not something a bot decides to start doing at them.
        return self::MODE_TEXT_ONLY;
    }

    /**
     * The same decision, once the answer exists.
     *
     * Only ever adds the written version. Dropping the audio here would spend
     * the generation and throw it away, and would take back a medium the
     * customer asked for; sending both costs one extra bubble and makes the
     * unusable half usable.
     *
     * @param  string  $decision  what decide() returned
     */
    public static function reconsider(string $decision, ?string $replyText, bool $handoff): string
    {
        if ($decision !== self::MODE_AUDIO_ONLY) {
            return $decision;
        }

        // Being handed to a human is the moment to be unambiguous, and the
        // note stays readable in the thread for whoever picks it up.
        if ($handoff) {
            return self::MODE_TEXT_AND_AUDIO;
        }

        return self::speakable((string) $replyText)
            ? self::MODE_AUDIO_ONLY
            : self::MODE_TEXT_AND_AUDIO;
    }

    /**
     * Whether this answer survives being heard rather than read.
     *
     * The test is about what the words carry, not about their tone: an address,
     * a credential or a code has to be copied, and you cannot copy from a
     * voice note.
     */
    public static function speakable(string $text): bool
    {
        $text = trim($text);

        if ($text === '' || Str::length($text) > self::LONG_ANSWER_CHARS) {
            return false;
        }

        foreach (self::UNSPEAKABLE as $pattern) {
            if (preg_match($pattern, $text)) {
                return false;
            }
        }

        // A walkthrough: three or more numbered steps. One "1." is a list of
        // one thing; three is something the customer will be following along
        // with, and they need it in front of them.
        return preg_match_all('~^\s*\d+[\).\-]\s+~m', $text) < 3;
    }

    /** True when this decision puts a voice note in front of the customer. */
    public static function speaks(string $decision): bool
    {
        return $decision === self::MODE_AUDIO_ONLY || $decision === self::MODE_TEXT_AND_AUDIO;
    }

    /** True when this decision also writes the answer out. */
    public static function writes(string $decision): bool
    {
        return $decision === self::MODE_TEXT_ONLY || $decision === self::MODE_TEXT_AND_AUDIO;
    }

    /** A known mode, or the fallback. Unknown values are never acted on. */
    public static function mode(mixed $value, string $fallback = self::MODE_DYNAMIC): string
    {
        $mode = is_string($value) ? strtolower(trim($value)) : '';

        return in_array($mode, self::MODES, true) ? $mode : $fallback;
    }
}
