<?php

namespace App\Services\Auth;

use BaconQrCode\Renderer\Image\SvgImageBackEnd;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;
use PragmaRX\Google2FA\Google2FA;

/**
 * Time-based one-time passwords, for any account that stores the three columns.
 *
 * Written against a model rather than against `User` because the two accounts
 * that need this are different tables: `admins` holds Back Office operators and
 * `users` holds customers, and the Back Office is the surface where a stolen
 * password reaches every workspace on the platform at once.
 *
 * ⚠️ Enrolment is two steps, and the second one is not ceremony. A secret
 * written straight to `two_factor_confirmed_at` locks the account to an
 * authenticator that may have failed to scan, mis-scanned, or been set up on a
 * phone whose clock is wrong — and the person finds out at their next sign-in,
 * from the outside. Nothing is enforced until a code generated by that secret
 * has come back.
 *
 * ⚠️ Recovery codes are hashed the way passwords are, not stored in the clear.
 * They are shown once, at the moment they are generated, and never again: a
 * readable copy in the database is a second password list, and the database is
 * exactly what an attacker who got this far already has.
 */
final class TwoFactor
{
    /** How many recovery codes an enrolment hands out. */
    public const RECOVERY_CODES = 8;

    /**
     * Windows of 30 seconds either side accepted.
     *
     * One step, not zero: phone clocks drift, and a person typing a six-digit
     * code at the end of its window is the normal case, not an attack. Each
     * extra step widens the guessing surface, so it stops at one.
     */
    private const WINDOW = 1;

    public function __construct(
        private readonly Google2FA $google2fa,
    ) {}

    /** A fresh secret, not yet attached to anything. */
    public function newSecret(): string
    {
        return $this->google2fa->generateSecretKey(32);
    }

    /** The `otpauth://` URI an authenticator app scans. */
    public function provisioningUri(string $holder, string $secret): string
    {
        return $this->google2fa->getQRCodeUrl(
            (string) config('app.name', 'Pingly'),
            $holder,
            $secret,
        );
    }

    /**
     * The provisioning URI as an inline SVG.
     *
     * SVG rather than a PNG data URI because it is rendered by the Back Office,
     * which has no image pipeline, and because the same markup stays sharp on
     * any screen. Served inside the JSON of an authenticated request and never
     * written to disk — the secret is in it.
     */
    public function qrSvg(string $holder, string $secret): string
    {
        $writer = new Writer(new ImageRenderer(
            new RendererStyle(280, 0),
            new SvgImageBackEnd(),
        ));

        return $writer->writeString($this->provisioningUri($holder, $secret));
    }

    /** Whether this code was generated by this secret, near enough to now. */
    public function verify(?string $secret, ?string $code): bool
    {
        $secret = (string) $secret;
        $code = preg_replace('/\D+/', '', (string) $code) ?? '';

        if ($secret === '' || strlen($code) !== 6) {
            return false;
        }

        try {
            return (bool) $this->google2fa->verifyKey($secret, $code, self::WINDOW);
        } catch (\Throwable) {
            // A malformed stored secret must read as "wrong code", never as a
            // 500 that tells the caller something about the account.
            return false;
        }
    }

    /**
     * A fresh set of recovery codes: the plaintext to show once, and the hashes
     * to store.
     *
     * @return array{plain: list<string>, hashed: list<string>}
     */
    public function newRecoveryCodes(): array
    {
        $plain = [];

        for ($i = 0; $i < self::RECOVERY_CODES; $i++) {
            $plain[] = Str::lower(Str::random(5).'-'.Str::random(5));
        }

        return [
            'plain' => $plain,
            'hashed' => array_map(static fn (string $code) => hash('sha256', $code), $plain),
        ];
    }

    /**
     * Spend a recovery code, if it is one of this account's.
     *
     * Single use: a code that survived being used is a password that never
     * expires. The remaining codes are written back by the caller.
     *
     * @param  list<string>  $hashed
     */
    public function consumeRecoveryCode(array &$hashed, ?string $code): bool
    {
        $candidate = hash('sha256', Str::lower(trim((string) $code)));

        foreach ($hashed as $index => $stored) {
            if (hash_equals((string) $stored, $candidate)) {
                unset($hashed[$index]);
                $hashed = array_values($hashed);

                return true;
            }
        }

        return false;
    }

    /** Whether this account has finished enrolling. */
    public function isEnabled(Model $account): bool
    {
        return $account->two_factor_confirmed_at !== null
            && ! empty($account->two_factor_secret);
    }

    /**
     * Park a password check that succeeded, and hand back the ticket for it.
     *
     * The second step of a sign-in needs to know the first one passed without
     * making the client hold the password, and without issuing a real token to
     * somebody who has not proved the second factor yet.
     *
     * ⚠️ Short-lived — five minutes — and spent the moment a code is accepted.
     * It is the password, in every sense that matters for the next few minutes,
     * so it is treated like one.
     *
     * ⚠️ Deliberately NOT consumed by a wrong code. Typing one digit wrong is
     * the ordinary case, and making that cost the password again would push
     * people towards turning the second factor off. What bounds guessing here
     * is the rate limit on the challenge endpoint, not the ticket.
     */
    public function issueChallenge(string $surface, Model $account): string
    {
        $token = Str::random(64);

        Cache::put($this->challengeKey($surface, $token), $account->getKey(), now()->addMinutes(5));

        return $token;
    }

    /** The account id behind a challenge ticket, without spending it. */
    public function readChallenge(string $surface, string $token): int|string|null
    {
        return Cache::get($this->challengeKey($surface, $token));
    }

    /** Spend the ticket. Called only once a code has been accepted. */
    public function consumeChallenge(string $surface, string $token): void
    {
        Cache::forget($this->challengeKey($surface, $token));
    }

    private function challengeKey(string $surface, string $token): string
    {
        return "two-factor-challenge:{$surface}:{$token}";
    }
}
