<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Two-factor columns for Back Office operators.
 *
 * `users` has carried these since the Fortify starter kit; `admins` was split
 * out of it later and never got them — which is how the most privileged
 * accounts on the platform ended up being the only ones that *could* not have
 * a second factor.
 *
 * Same column names as `users` so App\Services\Auth\TwoFactor can work against
 * either table without knowing which one it has.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('admins', function (Blueprint $table) {
            // Encrypted at the model, so text rather than string: ciphertext is
            // several times longer than the 32-character secret inside it.
            $table->text('two_factor_secret')->nullable()->after('password');
            $table->text('two_factor_recovery_codes')->nullable()->after('two_factor_secret');

            // Null until a code generated by the secret has come back. Until
            // then the account still signs in with a password alone — see
            // TwoFactor for why enrolment is two steps.
            $table->timestamp('two_factor_confirmed_at')->nullable()->after('two_factor_recovery_codes');
        });
    }

    public function down(): void
    {
        Schema::table('admins', function (Blueprint $table) {
            $table->dropColumn(['two_factor_secret', 'two_factor_recovery_codes', 'two_factor_confirmed_at']);
        });
    }
};
